// GENERATED by tools/build_map_data.py from tools/standard.map — do not edit by hand.

export const POWERS = [
  "austria",
  "england",
  "france",
  "germany",
  "italy",
  "russia",
  "turkey"
];

// province id -> { name, type: 'water'|'land'|'coast', sc, coasts: []|['ec','sc']|['nc','sc'] }
export const PROVINCES = {
  "adr": {
    "coasts": [],
    "name": "Adriatic Sea",
    "sc": false,
    "type": "water"
  },
  "aeg": {
    "coasts": [],
    "name": "Aegean Sea",
    "sc": false,
    "type": "water"
  },
  "alb": {
    "coasts": [],
    "name": "Albania",
    "sc": false,
    "type": "coast"
  },
  "ank": {
    "coasts": [],
    "name": "Ankara",
    "sc": true,
    "type": "coast"
  },
  "apu": {
    "coasts": [],
    "name": "Apulia",
    "sc": false,
    "type": "coast"
  },
  "arm": {
    "coasts": [],
    "name": "Armenia",
    "sc": false,
    "type": "coast"
  },
  "bal": {
    "coasts": [],
    "name": "Baltic Sea",
    "sc": false,
    "type": "water"
  },
  "bar": {
    "coasts": [],
    "name": "Barents Sea",
    "sc": false,
    "type": "water"
  },
  "bel": {
    "coasts": [],
    "name": "Belgium",
    "sc": true,
    "type": "coast"
  },
  "ber": {
    "coasts": [],
    "name": "Berlin",
    "sc": true,
    "type": "coast"
  },
  "bla": {
    "coasts": [],
    "name": "Black Sea",
    "sc": false,
    "type": "water"
  },
  "boh": {
    "coasts": [],
    "name": "Bohemia",
    "sc": false,
    "type": "land"
  },
  "bot": {
    "coasts": [],
    "name": "Gulf of Bothnia",
    "sc": false,
    "type": "water"
  },
  "bre": {
    "coasts": [],
    "name": "Brest",
    "sc": true,
    "type": "coast"
  },
  "bud": {
    "coasts": [],
    "name": "Budapest",
    "sc": true,
    "type": "land"
  },
  "bul": {
    "coasts": [
      "ec",
      "sc"
    ],
    "name": "Bulgaria",
    "sc": true,
    "type": "coast"
  },
  "bur": {
    "coasts": [],
    "name": "Burgundy",
    "sc": false,
    "type": "land"
  },
  "cly": {
    "coasts": [],
    "name": "Clyde",
    "sc": false,
    "type": "coast"
  },
  "con": {
    "coasts": [],
    "name": "Constantinople",
    "sc": true,
    "type": "coast"
  },
  "den": {
    "coasts": [],
    "name": "Denmark",
    "sc": true,
    "type": "coast"
  },
  "eas": {
    "coasts": [],
    "name": "Eastern Mediterranean",
    "sc": false,
    "type": "water"
  },
  "edi": {
    "coasts": [],
    "name": "Edinburgh",
    "sc": true,
    "type": "coast"
  },
  "eng": {
    "coasts": [],
    "name": "English Channel",
    "sc": false,
    "type": "water"
  },
  "fin": {
    "coasts": [],
    "name": "Finland",
    "sc": false,
    "type": "coast"
  },
  "gal": {
    "coasts": [],
    "name": "Galicia",
    "sc": false,
    "type": "land"
  },
  "gas": {
    "coasts": [],
    "name": "Gascony",
    "sc": false,
    "type": "coast"
  },
  "gre": {
    "coasts": [],
    "name": "Greece",
    "sc": true,
    "type": "coast"
  },
  "hel": {
    "coasts": [],
    "name": "Helgoland Bight",
    "sc": false,
    "type": "water"
  },
  "hol": {
    "coasts": [],
    "name": "Holland",
    "sc": true,
    "type": "coast"
  },
  "ion": {
    "coasts": [],
    "name": "Ionian Sea",
    "sc": false,
    "type": "water"
  },
  "iri": {
    "coasts": [],
    "name": "Irish Sea",
    "sc": false,
    "type": "water"
  },
  "kie": {
    "coasts": [],
    "name": "Kiel",
    "sc": true,
    "type": "coast"
  },
  "lon": {
    "coasts": [],
    "name": "London",
    "sc": true,
    "type": "coast"
  },
  "lvn": {
    "coasts": [],
    "name": "Livonia",
    "sc": false,
    "type": "coast"
  },
  "lvp": {
    "coasts": [],
    "name": "Liverpool",
    "sc": true,
    "type": "coast"
  },
  "lyo": {
    "coasts": [],
    "name": "Gulf of Lyon",
    "sc": false,
    "type": "water"
  },
  "mao": {
    "coasts": [],
    "name": "Mid-Atlantic Ocean",
    "sc": false,
    "type": "water"
  },
  "mar": {
    "coasts": [],
    "name": "Marseilles",
    "sc": true,
    "type": "coast"
  },
  "mos": {
    "coasts": [],
    "name": "Moscow",
    "sc": true,
    "type": "land"
  },
  "mun": {
    "coasts": [],
    "name": "Munich",
    "sc": true,
    "type": "land"
  },
  "naf": {
    "coasts": [],
    "name": "North Africa",
    "sc": false,
    "type": "coast"
  },
  "nao": {
    "coasts": [],
    "name": "North Atlantic Ocean",
    "sc": false,
    "type": "water"
  },
  "nap": {
    "coasts": [],
    "name": "Naples",
    "sc": true,
    "type": "coast"
  },
  "nth": {
    "coasts": [],
    "name": "North Sea",
    "sc": false,
    "type": "water"
  },
  "nwg": {
    "coasts": [],
    "name": "Norwegian Sea",
    "sc": false,
    "type": "water"
  },
  "nwy": {
    "coasts": [],
    "name": "Norway",
    "sc": true,
    "type": "coast"
  },
  "par": {
    "coasts": [],
    "name": "Paris",
    "sc": true,
    "type": "land"
  },
  "pic": {
    "coasts": [],
    "name": "Picardy",
    "sc": false,
    "type": "coast"
  },
  "pie": {
    "coasts": [],
    "name": "Piedmont",
    "sc": false,
    "type": "coast"
  },
  "por": {
    "coasts": [],
    "name": "Portugal",
    "sc": true,
    "type": "coast"
  },
  "pru": {
    "coasts": [],
    "name": "Prussia",
    "sc": false,
    "type": "coast"
  },
  "rom": {
    "coasts": [],
    "name": "Rome",
    "sc": true,
    "type": "coast"
  },
  "ruh": {
    "coasts": [],
    "name": "Ruhr",
    "sc": false,
    "type": "land"
  },
  "rum": {
    "coasts": [],
    "name": "Rumania",
    "sc": true,
    "type": "coast"
  },
  "ser": {
    "coasts": [],
    "name": "Serbia",
    "sc": true,
    "type": "land"
  },
  "sev": {
    "coasts": [],
    "name": "Sevastopol",
    "sc": true,
    "type": "coast"
  },
  "sil": {
    "coasts": [],
    "name": "Silesia",
    "sc": false,
    "type": "land"
  },
  "ska": {
    "coasts": [],
    "name": "Skagerrak",
    "sc": false,
    "type": "water"
  },
  "smy": {
    "coasts": [],
    "name": "Smyrna",
    "sc": true,
    "type": "coast"
  },
  "spa": {
    "coasts": [
      "nc",
      "sc"
    ],
    "name": "Spain",
    "sc": true,
    "type": "coast"
  },
  "stp": {
    "coasts": [
      "nc",
      "sc"
    ],
    "name": "St Petersburg",
    "sc": true,
    "type": "coast"
  },
  "swe": {
    "coasts": [],
    "name": "Sweden",
    "sc": true,
    "type": "coast"
  },
  "syr": {
    "coasts": [],
    "name": "Syria",
    "sc": false,
    "type": "coast"
  },
  "tri": {
    "coasts": [],
    "name": "Trieste",
    "sc": true,
    "type": "coast"
  },
  "tun": {
    "coasts": [],
    "name": "Tunis",
    "sc": true,
    "type": "coast"
  },
  "tus": {
    "coasts": [],
    "name": "Tuscany",
    "sc": false,
    "type": "coast"
  },
  "tyr": {
    "coasts": [],
    "name": "Tyrolia",
    "sc": false,
    "type": "land"
  },
  "tys": {
    "coasts": [],
    "name": "Tyrrhenian Sea",
    "sc": false,
    "type": "water"
  },
  "ukr": {
    "coasts": [],
    "name": "Ukraine",
    "sc": false,
    "type": "land"
  },
  "ven": {
    "coasts": [],
    "name": "Venice",
    "sc": true,
    "type": "coast"
  },
  "vie": {
    "coasts": [],
    "name": "Vienna",
    "sc": true,
    "type": "land"
  },
  "wal": {
    "coasts": [],
    "name": "Wales",
    "sc": false,
    "type": "coast"
  },
  "war": {
    "coasts": [],
    "name": "Warsaw",
    "sc": true,
    "type": "land"
  },
  "wes": {
    "coasts": [],
    "name": "Western Mediterranean",
    "sc": false,
    "type": "water"
  },
  "yor": {
    "coasts": [],
    "name": "Yorkshire",
    "sc": false,
    "type": "coast"
  }
};

// army adjacency: province -> [province]
export const ARMY_ADJ = {
  "alb": [
    "gre",
    "ser",
    "tri"
  ],
  "ank": [
    "arm",
    "con",
    "smy"
  ],
  "apu": [
    "nap",
    "rom",
    "ven"
  ],
  "arm": [
    "ank",
    "sev",
    "smy",
    "syr"
  ],
  "bel": [
    "bur",
    "hol",
    "pic",
    "ruh"
  ],
  "ber": [
    "kie",
    "mun",
    "pru",
    "sil"
  ],
  "boh": [
    "gal",
    "mun",
    "sil",
    "tyr",
    "vie"
  ],
  "bre": [
    "gas",
    "par",
    "pic"
  ],
  "bud": [
    "gal",
    "rum",
    "ser",
    "tri",
    "vie"
  ],
  "bul": [
    "con",
    "gre",
    "rum",
    "ser"
  ],
  "bur": [
    "bel",
    "gas",
    "mar",
    "mun",
    "par",
    "pic",
    "ruh"
  ],
  "cly": [
    "edi",
    "lvp"
  ],
  "con": [
    "ank",
    "bul",
    "smy"
  ],
  "den": [
    "kie",
    "swe"
  ],
  "edi": [
    "cly",
    "lvp",
    "yor"
  ],
  "fin": [
    "nwy",
    "stp",
    "swe"
  ],
  "gal": [
    "boh",
    "bud",
    "rum",
    "sil",
    "ukr",
    "vie",
    "war"
  ],
  "gas": [
    "bre",
    "bur",
    "mar",
    "par",
    "spa"
  ],
  "gre": [
    "alb",
    "bul",
    "ser"
  ],
  "hol": [
    "bel",
    "kie",
    "ruh"
  ],
  "kie": [
    "ber",
    "den",
    "hol",
    "mun",
    "ruh"
  ],
  "lon": [
    "wal",
    "yor"
  ],
  "lvn": [
    "mos",
    "pru",
    "stp",
    "war"
  ],
  "lvp": [
    "cly",
    "edi",
    "wal",
    "yor"
  ],
  "mar": [
    "bur",
    "gas",
    "pie",
    "spa"
  ],
  "mos": [
    "lvn",
    "sev",
    "stp",
    "ukr",
    "war"
  ],
  "mun": [
    "ber",
    "boh",
    "bur",
    "kie",
    "ruh",
    "sil",
    "tyr"
  ],
  "naf": [
    "tun"
  ],
  "nap": [
    "apu",
    "rom"
  ],
  "nwy": [
    "fin",
    "stp",
    "swe"
  ],
  "par": [
    "bre",
    "bur",
    "gas",
    "pic"
  ],
  "pic": [
    "bel",
    "bre",
    "bur",
    "par"
  ],
  "pie": [
    "mar",
    "tus",
    "tyr",
    "ven"
  ],
  "por": [
    "spa"
  ],
  "pru": [
    "ber",
    "lvn",
    "sil",
    "war"
  ],
  "rom": [
    "apu",
    "nap",
    "tus",
    "ven"
  ],
  "ruh": [
    "bel",
    "bur",
    "hol",
    "kie",
    "mun"
  ],
  "rum": [
    "bud",
    "bul",
    "gal",
    "ser",
    "sev",
    "ukr"
  ],
  "ser": [
    "alb",
    "bud",
    "bul",
    "gre",
    "rum",
    "tri"
  ],
  "sev": [
    "arm",
    "mos",
    "rum",
    "ukr"
  ],
  "sil": [
    "ber",
    "boh",
    "gal",
    "mun",
    "pru",
    "war"
  ],
  "smy": [
    "ank",
    "arm",
    "con",
    "syr"
  ],
  "spa": [
    "gas",
    "mar",
    "por"
  ],
  "stp": [
    "fin",
    "lvn",
    "mos",
    "nwy"
  ],
  "swe": [
    "den",
    "fin",
    "nwy"
  ],
  "syr": [
    "arm",
    "smy"
  ],
  "tri": [
    "alb",
    "bud",
    "ser",
    "tyr",
    "ven",
    "vie"
  ],
  "tun": [
    "naf"
  ],
  "tus": [
    "pie",
    "rom",
    "ven"
  ],
  "tyr": [
    "boh",
    "mun",
    "pie",
    "tri",
    "ven",
    "vie"
  ],
  "ukr": [
    "gal",
    "mos",
    "rum",
    "sev",
    "war"
  ],
  "ven": [
    "apu",
    "pie",
    "rom",
    "tri",
    "tus",
    "tyr"
  ],
  "vie": [
    "boh",
    "bud",
    "gal",
    "tri",
    "tyr"
  ],
  "wal": [
    "lon",
    "lvp",
    "yor"
  ],
  "war": [
    "gal",
    "lvn",
    "mos",
    "pru",
    "sil",
    "ukr"
  ],
  "yor": [
    "edi",
    "lon",
    "lvp",
    "wal"
  ]
};

// fleet adjacency: location -> [location]  (location = 'pro' or 'pro/coast')
export const FLEET_ADJ = {
  "adr": [
    "alb",
    "apu",
    "ion",
    "tri",
    "ven"
  ],
  "aeg": [
    "bul/sc",
    "con",
    "eas",
    "gre",
    "ion",
    "smy"
  ],
  "alb": [
    "adr",
    "gre",
    "ion",
    "tri"
  ],
  "ank": [
    "arm",
    "bla",
    "con"
  ],
  "apu": [
    "adr",
    "ion",
    "nap",
    "ven"
  ],
  "arm": [
    "ank",
    "bla",
    "sev"
  ],
  "bal": [
    "ber",
    "bot",
    "den",
    "kie",
    "lvn",
    "pru",
    "swe"
  ],
  "bar": [
    "nwg",
    "nwy",
    "stp/nc"
  ],
  "bel": [
    "eng",
    "hol",
    "nth",
    "pic"
  ],
  "ber": [
    "bal",
    "kie",
    "pru"
  ],
  "bla": [
    "ank",
    "arm",
    "bul/ec",
    "con",
    "rum",
    "sev"
  ],
  "bot": [
    "bal",
    "fin",
    "lvn",
    "stp/sc",
    "swe"
  ],
  "bre": [
    "eng",
    "gas",
    "mao",
    "pic"
  ],
  "bul/ec": [
    "bla",
    "con",
    "rum"
  ],
  "bul/sc": [
    "aeg",
    "con",
    "gre"
  ],
  "cly": [
    "edi",
    "lvp",
    "nao",
    "nwg"
  ],
  "con": [
    "aeg",
    "ank",
    "bla",
    "bul/ec",
    "bul/sc",
    "smy"
  ],
  "den": [
    "bal",
    "hel",
    "kie",
    "nth",
    "ska",
    "swe"
  ],
  "eas": [
    "aeg",
    "ion",
    "smy",
    "syr"
  ],
  "edi": [
    "cly",
    "nth",
    "nwg",
    "yor"
  ],
  "eng": [
    "bel",
    "bre",
    "iri",
    "lon",
    "mao",
    "nth",
    "pic",
    "wal"
  ],
  "fin": [
    "bot",
    "stp/sc",
    "swe"
  ],
  "gas": [
    "bre",
    "mao",
    "spa/nc"
  ],
  "gre": [
    "aeg",
    "alb",
    "bul/sc",
    "ion"
  ],
  "hel": [
    "den",
    "hol",
    "kie",
    "nth"
  ],
  "hol": [
    "bel",
    "hel",
    "kie",
    "nth"
  ],
  "ion": [
    "adr",
    "aeg",
    "alb",
    "apu",
    "eas",
    "gre",
    "nap",
    "tun",
    "tys"
  ],
  "iri": [
    "eng",
    "lvp",
    "mao",
    "nao",
    "wal"
  ],
  "kie": [
    "bal",
    "ber",
    "den",
    "hel",
    "hol"
  ],
  "lon": [
    "eng",
    "nth",
    "wal",
    "yor"
  ],
  "lvn": [
    "bal",
    "bot",
    "pru",
    "stp/sc"
  ],
  "lvp": [
    "cly",
    "iri",
    "nao",
    "wal"
  ],
  "lyo": [
    "mar",
    "pie",
    "spa/sc",
    "tus",
    "tys",
    "wes"
  ],
  "mao": [
    "bre",
    "eng",
    "gas",
    "iri",
    "naf",
    "nao",
    "por",
    "spa/nc",
    "spa/sc",
    "wes"
  ],
  "mar": [
    "lyo",
    "pie",
    "spa/sc"
  ],
  "naf": [
    "mao",
    "tun",
    "wes"
  ],
  "nao": [
    "cly",
    "iri",
    "lvp",
    "mao",
    "nwg"
  ],
  "nap": [
    "apu",
    "ion",
    "rom",
    "tys"
  ],
  "nth": [
    "bel",
    "den",
    "edi",
    "eng",
    "hel",
    "hol",
    "lon",
    "nwg",
    "nwy",
    "ska",
    "yor"
  ],
  "nwg": [
    "bar",
    "cly",
    "edi",
    "nao",
    "nth",
    "nwy"
  ],
  "nwy": [
    "bar",
    "nth",
    "nwg",
    "ska",
    "stp/nc",
    "swe"
  ],
  "pic": [
    "bel",
    "bre",
    "eng"
  ],
  "pie": [
    "lyo",
    "mar",
    "tus"
  ],
  "por": [
    "mao",
    "spa/nc",
    "spa/sc"
  ],
  "pru": [
    "bal",
    "ber",
    "lvn"
  ],
  "rom": [
    "nap",
    "tus",
    "tys"
  ],
  "rum": [
    "bla",
    "bul/ec",
    "sev"
  ],
  "sev": [
    "arm",
    "bla",
    "rum"
  ],
  "ska": [
    "den",
    "nth",
    "nwy",
    "swe"
  ],
  "smy": [
    "aeg",
    "con",
    "eas",
    "syr"
  ],
  "spa/nc": [
    "gas",
    "mao",
    "por"
  ],
  "spa/sc": [
    "lyo",
    "mao",
    "mar",
    "por",
    "wes"
  ],
  "stp/nc": [
    "bar",
    "nwy"
  ],
  "stp/sc": [
    "bot",
    "fin",
    "lvn"
  ],
  "swe": [
    "bal",
    "bot",
    "den",
    "fin",
    "nwy",
    "ska"
  ],
  "syr": [
    "eas",
    "smy"
  ],
  "tri": [
    "adr",
    "alb",
    "ven"
  ],
  "tun": [
    "ion",
    "naf",
    "tys",
    "wes"
  ],
  "tus": [
    "lyo",
    "pie",
    "rom",
    "tys"
  ],
  "tys": [
    "ion",
    "lyo",
    "nap",
    "rom",
    "tun",
    "tus",
    "wes"
  ],
  "ven": [
    "adr",
    "apu",
    "tri"
  ],
  "wal": [
    "eng",
    "iri",
    "lon",
    "lvp"
  ],
  "wes": [
    "lyo",
    "mao",
    "naf",
    "spa/sc",
    "tun",
    "tys"
  ],
  "yor": [
    "edi",
    "lon",
    "nth"
  ]
};

// power -> home supply centers
export const HOME_CENTERS = {
  "austria": [
    "bud",
    "tri",
    "vie"
  ],
  "england": [
    "edi",
    "lon",
    "lvp"
  ],
  "france": [
    "bre",
    "mar",
    "par"
  ],
  "germany": [
    "ber",
    "kie",
    "mun"
  ],
  "italy": [
    "nap",
    "rom",
    "ven"
  ],
  "russia": [
    "mos",
    "sev",
    "stp",
    "war"
  ],
  "turkey": [
    "ank",
    "con",
    "smy"
  ]
};

// supply center -> starting owner (null = neutral)
export const START_OWNERS = {
  "ank": "turkey",
  "bel": null,
  "ber": "germany",
  "bre": "france",
  "bud": "austria",
  "bul": null,
  "con": "turkey",
  "den": null,
  "edi": "england",
  "gre": null,
  "hol": null,
  "kie": "germany",
  "lon": "england",
  "lvp": "england",
  "mar": "france",
  "mos": "russia",
  "mun": "germany",
  "nap": "italy",
  "nwy": null,
  "par": "france",
  "por": null,
  "rom": "italy",
  "rum": null,
  "ser": null,
  "sev": "russia",
  "smy": "turkey",
  "spa": null,
  "stp": "russia",
  "swe": null,
  "tri": "austria",
  "tun": null,
  "ven": "italy",
  "vie": "austria",
  "war": "russia"
};

// power -> starting units
export const START_UNITS = {
  "austria": [
    {
      "loc": "bud",
      "type": "A"
    },
    {
      "loc": "vie",
      "type": "A"
    },
    {
      "loc": "tri",
      "type": "F"
    }
  ],
  "england": [
    {
      "loc": "edi",
      "type": "F"
    },
    {
      "loc": "lon",
      "type": "F"
    },
    {
      "loc": "lvp",
      "type": "A"
    }
  ],
  "france": [
    {
      "loc": "bre",
      "type": "F"
    },
    {
      "loc": "mar",
      "type": "A"
    },
    {
      "loc": "par",
      "type": "A"
    }
  ],
  "germany": [
    {
      "loc": "kie",
      "type": "F"
    },
    {
      "loc": "ber",
      "type": "A"
    },
    {
      "loc": "mun",
      "type": "A"
    }
  ],
  "italy": [
    {
      "loc": "nap",
      "type": "F"
    },
    {
      "loc": "rom",
      "type": "A"
    },
    {
      "loc": "ven",
      "type": "A"
    }
  ],
  "russia": [
    {
      "loc": "war",
      "type": "A"
    },
    {
      "loc": "mos",
      "type": "A"
    },
    {
      "loc": "sev",
      "type": "F"
    },
    {
      "loc": "stp/sc",
      "type": "F"
    }
  ],
  "turkey": [
    {
      "loc": "ank",
      "type": "F"
    },
    {
      "loc": "con",
      "type": "A"
    },
    {
      "loc": "smy",
      "type": "A"
    }
  ]
};

// lowercase alias -> canonical location
export const ALIASES = {
  "adr": "adr",
  "adriatic": "adr",
  "adriatic sea": "adr",
  "aeg": "aeg",
  "aegean": "aeg",
  "aegean sea": "aeg",
  "alb": "alb",
  "albania": "alb",
  "ank": "ank",
  "ankara": "ank",
  "apu": "apu",
  "apulia": "apu",
  "arm": "arm",
  "armenia": "arm",
  "bal": "bal",
  "baltic": "bal",
  "baltic sea": "bal",
  "bar": "bar",
  "barents": "bar",
  "barents sea": "bar",
  "bel": "bel",
  "belgium": "bel",
  "ber": "ber",
  "berl": "ber",
  "berlin": "ber",
  "bla": "bla",
  "black": "bla",
  "black sea": "bla",
  "boh": "boh",
  "bohemia": "boh",
  "bot": "bot",
  "both": "bot",
  "bothnia": "bot",
  "bre": "bre",
  "brest": "bre",
  "bs": "bla",
  "bud": "bud",
  "budapest": "bud",
  "bul": "bul",
  "bul(ec)": "bul/ec",
  "bul(nc)": "bul/ec",
  "bul(sc)": "bul/sc",
  "bul/ec": "bul/ec",
  "bul/nc": "bul/ec",
  "bul/sc": "bul/sc",
  "bulg": "bul",
  "bulgaria": "bul",
  "bulgaria (east coast)": "bul/ec",
  "bulgaria (south coast)": "bul/sc",
  "bulgaria(ec)": "bul/ec",
  "bulgaria(nc)": "bul/ec",
  "bulgaria(sc)": "bul/sc",
  "bulgaria/ec": "bul/ec",
  "bulgaria/nc": "bul/ec",
  "bulgaria/sc": "bul/sc",
  "bur": "bur",
  "burg": "bur",
  "burgandy": "bur",
  "burgundy": "bur",
  "channel": "eng",
  "cly": "cly",
  "clyde": "cly",
  "con": "con",
  "constantinople": "con",
  "den": "den",
  "denmark": "den",
  "eas": "eas",
  "eas med": "eas",
  "east": "eas",
  "eastern": "eas",
  "eastern mediterranean": "eas",
  "eastmed": "eas",
  "ech": "eng",
  "edi": "edi",
  "edinburgh": "edi",
  "emd": "eas",
  "eme": "eas",
  "emed": "eas",
  "ems": "eas",
  "eng": "eng",
  "eng ch": "eng",
  "english channel": "eng",
  "fin": "fin",
  "finland": "fin",
  "gal": "gal",
  "galacia": "gal",
  "galicia": "gal",
  "gas": "gas",
  "gasc": "gas",
  "gascony": "gas",
  "gob": "bot",
  "gol": "lyo",
  "gre": "gre",
  "greece": "gre",
  "gulf of bothnia": "bot",
  "gulf of lyon": "lyo",
  "gulf of lyons": "lyo",
  "gulfofb": "bot",
  "gulfofl": "lyo",
  "hel": "hel",
  "helg": "hel",
  "helgoland": "hel",
  "helgoland bight": "hel",
  "heligoland": "hel",
  "heligoland bight": "hel",
  "hol": "hol",
  "holland": "hol",
  "ion": "ion",
  "ionian": "ion",
  "ionian sea": "ion",
  "iri": "iri",
  "irish": "iri",
  "irish sea": "iri",
  "irs": "iri",
  "kie": "kie",
  "kiel": "kie",
  "liv": "lvn",
  "liverpool": "lvp",
  "livo": "lvn",
  "livon": "lvn",
  "livonia": "lvn",
  "livp": "lvp",
  "lon": "lon",
  "london": "lon",
  "lpl": "lvp",
  "lva": "lvn",
  "lvn": "lvn",
  "lvo": "lvn",
  "lvp": "lvp",
  "lyo": "lyo",
  "lyon": "lyo",
  "lyons": "lyo",
  "mao": "mao",
  "mar": "mar",
  "mars": "mar",
  "marseilles": "mar",
  "mat": "mao",
  "mid": "mao",
  "mid-atlantic ocean": "mao",
  "midatlantic": "mao",
  "midatlanticocean": "mao",
  "mos": "mos",
  "moscow": "mos",
  "mun": "mun",
  "munich": "mun",
  "n afr": "naf",
  "na": "nao",
  "naf": "naf",
  "nao": "nao",
  "nap": "nap",
  "naples": "nap",
  "nat": "nao",
  "nor": "nwy",
  "nora": "naf",
  "norg": "nwg",
  "norsea": "nth",
  "north africa": "naf",
  "north atlantic ocean": "nao",
  "north sea": "nth",
  "norw": "nwy",
  "norway": "nwy",
  "norwegian": "nwg",
  "norwegian sea": "nwg",
  "norwsea": "nwg",
  "nrg": "nwg",
  "ns": "nth",
  "nth": "nth",
  "nts": "nth",
  "nwg": "nwg",
  "nwy": "nwy",
  "par": "par",
  "paris": "par",
  "pic": "pic",
  "picardy": "pic",
  "pid": "pie",
  "pie": "pie",
  "piedmont": "pie",
  "por": "por",
  "port": "por",
  "portugal": "por",
  "pru": "pru",
  "prus": "pru",
  "prussia": "pru",
  "rom": "rom",
  "romania": "rum",
  "rome": "rom",
  "ruh": "ruh",
  "ruhr": "ruh",
  "rum": "rum",
  "rumania": "rum",
  "ser": "ser",
  "serb": "ser",
  "serbia": "ser",
  "sev": "sev",
  "seva": "sev",
  "sevast": "sev",
  "sevastapol": "sev",
  "sevastopol": "sev",
  "sil": "sil",
  "silesia": "sil",
  "ska": "ska",
  "skag": "ska",
  "skagerrack": "ska",
  "skagerrak": "ska",
  "smy": "smy",
  "smyrna": "smy",
  "spa": "spa",
  "spa (north coast)": "spa/nc",
  "spa (south coast)": "spa/sc",
  "spa(nc)": "spa/nc",
  "spa(sc)": "spa/sc",
  "spa/nc": "spa/nc",
  "spa/sc": "spa/sc",
  "spa/wc": "spa/sc",
  "spain": "spa",
  "spain (north coast)": "spa/nc",
  "spain (south coast)": "spa/sc",
  "spain(nc)": "spa/nc",
  "spain(sc)": "spa/sc",
  "spain/nc": "spa/nc",
  "spain/sc": "spa/sc",
  "spn": "spa",
  "spn(nc)": "spa/nc",
  "spn(sc)": "spa/sc",
  "spn/nc": "spa/nc",
  "spn/sc": "spa/sc",
  "st petersburg": "stp",
  "st petersburg (north coast)": "stp/nc",
  "st petersburg (south coast)": "stp/sc",
  "st. petersburg": "stp",
  "st. petersburg/nc": "stp/nc",
  "st. petersburg/sc": "stp/sc",
  "st.petersburg": "stp",
  "stp": "stp",
  "stp (north coast)": "stp/nc",
  "stp (south coast)": "stp/sc",
  "stp(nc)": "stp/nc",
  "stp(sc)": "stp/sc",
  "stp/nc": "stp/nc",
  "stp/sc": "stp/sc",
  "stpete": "stp",
  "stpete(nc)": "stp/nc",
  "stpete(sc)": "stp/sc",
  "stpete/nc": "stp/nc",
  "stpete/sc": "stp/sc",
  "swe": "swe",
  "sweden": "swe",
  "swi": "swi",
  "switzerland": "swi",
  "syr": "syr",
  "syria": "syr",
  "tri": "tri",
  "trieste": "tri",
  "trl": "tyr",
  "tun": "tun",
  "tunis": "tun",
  "tus": "tus",
  "tusc": "tus",
  "tuscany": "tus",
  "tyh": "tys",
  "tyl": "tyr",
  "tyn": "tys",
  "tyo": "tyr",
  "tyr": "tyr",
  "tyrhh": "tys",
  "tyrol": "tyr",
  "tyrolia": "tyr",
  "tyrr": "tys",
  "tyrrhenian": "tys",
  "tyrrhenian sea": "tys",
  "tys": "tys",
  "ukr": "ukr",
  "ukraine": "ukr",
  "ven": "ven",
  "venice": "ven",
  "vie": "vie",
  "vien": "vie",
  "vienna": "vie",
  "wal": "wal",
  "wales": "wal",
  "war": "war",
  "warsaw": "war",
  "wes": "wes",
  "wes med": "wes",
  "west": "wes",
  "west med": "wes",
  "western": "wes",
  "western med": "wes",
  "western mediterranean": "wes",
  "westmed": "wes",
  "wmd": "wes",
  "wme": "wes",
  "wmed": "wes",
  "wms": "wes",
  "yonkers": "yor",
  "yor": "yor",
  "york": "yor",
  "yorkshire": "yor"
};
